language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t amol9372/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amol9372/react-test npm test -- --coverage

after_success:
  - docker build -t amol9372/multi-client ./client
  - docker build -t amol9372/multi-server ./server
  - docker build -t amol9372/multi-nginx ./nginx
  - docker build -t amol9372/multi-worker ./worker
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push amol9372/multi-client
  - docker push amol9372/multi-server
  - docker push amol9372/multi-nginx
  - docker push amol9372/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-319897880590"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
