version: "3"
services:
  nginx:
    image: "amol9372/multi-nginx"
    depends_on:
      - api
      - client
    restart: always
    ports:
      - "80:80"
    mem_limit: 128m
  api:
    image: "amol9372/multi-server"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT
    hostname: api
    mem_limit: 128m
  client:
    stdin_open: true
    image: "amol9372/multi-client"
    mem_limit: 128m
    hostname: client
  worker:
    image: "amol9372/multi-worker"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    mem_limit: 128m
